main: com.Gbserver.Main
version: 5.49
name: Broadwell Server Plugin
depend: [LibsDisguises, ProtocolLib]

commands:
  spawn:
    description: This command gets you back to the original spawn point.
  tell:
    description: Tells a secret message.
    usage: /tell <player> <message>
    aliases: [t, msg, m]
  runner:
    description: Runner Minigame commands.
    usage: addPlayer, removePlayer, begin, stop, reset.
  protection:
    description: World Protection commands.
    usage: set, exclude.
  afk:
    description: Toggles AFK tag.
  isafk:
    description: Queries for if a player is AFK.
    usage: /isafk <query target player>
  broadcast:
    description: Broadcasts a message boldly.
    usage: /broadcast <message>
    aliases: [bc]
  back:
    description: Takes the player back to his/her original death location after a respawn.
  nick:
    description: Names a specified entity.
    usage: /nick <name/uname> <nickname> (nickname only required when using name)
  ride:
    description: Rides a specified entity.
  rideme:
    description: Makes a specified entity ride you.
  save:
    description: Saves a person's inventory, location, and potion effects.
    usage: /save <player>
  rest:
    description: Restores a person's inventory, location, and potion effects.
    usage: /restore <player>
  gm:
    description: Changes a person's gamemode.
    usage: /gm c/s/p (c=Creative,s=Survival,p=Spectator)
  bl:
    description: Bomb Lobbers commands.
    usage: /bl <addPlayer/start/reset> [player]
  heal:
    description: Heals a specified Living Entity.
  tf:
    description: Opens the Turf Wars menu.
  menu:
    description: Opens the command menu.
  sit:
    description: Sits on a block.
  announce:
    description: Adds a broadcast message to the broadcast system.
    usage: /announce add <broadcast message>
  friend:
    description: It's a secret.
    aliases: [f]
  vote:
    description: Vote commands.
    usage: It's complicated.
  mute:
    description: Mute a player.
  protect:
    description: Make a LivingEntity invincible.
  quit:
    description: Custom quit messages.
    usage: /quit [ragequit/afk/die]
  nofall:
    description: Toggles fall damage.
    usage: 
  tpa:
    description: Teleportation Requests.
    usage:
  tpaccept:
    description: Accepts a teleportation request.
    usage:
  tpdeny:
    description: Denys a teleportation request.
    usage: 
  tphere:
    description: Teleportation requests to yourself.
    usage:
  lobby:
    description: Lobby Join/Leave.
    usage: 
  ctf:
    description: Capture the flag!
    usage: 
  home:
    description: Save your home.
    aliases: [sethome]
  say:
    description: Disabled command.
  ignore:
    description: Ignoring chat messages.
  bacon:
    description: All about Bacon Brawl.
  hat:
    description: Enjoy hats!
  warp:
    description: Save and use waypoints.
  admin:
    description: Talk to an admin.
    usage: /admin <message>
    aliases: [a]
  devops:
    description: Developer Operations (limited permissions)
  group:
    description: Group chat (party)
    aliases: [g]
  reply:
    description: Reply a person that has messaged you.
    aliases: [r]
  mail:
    description: Send and receive mail.
  ping:
    description: Pong!
  twitch:
    description: Streamer utilities.
  selscript:
    description: SelectorScript experiments.
  skull:
    description: Get a fresh skull of a player.
  weather:
    description: Change the weather easier.
    aliases: [w]
  marry:
    description: <3
  jail:
    description: Prison.
  day:
    description: Set time to day.
  night:
    description: Set time to night.
  spec:
    description: Spectate a specified player.
  survival:
    description: Toggle Survival mode.
    aliases: [surv]
  contractverify:
    description: Have you read the contract yet?
  uptime:
    description: Calculates your uptime.